version: '3.3'

services:
  aspnetapp:
    build: ../010-exercise-1-dockerfile
    ports:
    - "8081:80"     # The HTTP port
    environment: 
      - ASPNETCORE_URLS=http://+:80
  vegeta:
    image: oba11/vegeta 
    command: sh -c "echo 'GET http://aspnetapp' | vegeta attack -duration=2m | tee results.bin | vegeta report"
    depends_on:
      - aspnetapp